CFG_DEST: run_config.yaml  # F!@0.05 = 0.770
DATA_LOADER:
  DATA_DIR: /mnt/SharedProject/Dataset/LOVEU_22/gebd
  IMG_SIZE: 224
DEBUG: false
DESC: ''
LOGGER: wandb
MODEL:
  BACKBONE: resnet_1
  FREEZE_BACKBONE: false
  FREEZE_BATCHNORM: true
  FROM_LOGITS: false
  LEVEL: s1230
  OUTPUT_DIM: 256
  PREDICTION_DIM: 1024
  SD_DILATION_RATES: -1
  SEQ_LEN: 50
  TPP_FEAT: true
NUM_GPUS: 1
OPTIM:
  BASE_LR: 0.0004
  LR_SCHEDULER: cosine
  LR_SCHEDULER_ALPHA: 0.01
  LR_SCHEDULER_DECAY_STEPS: 8
  MOMENTUM: 0.9
  NAME: adam
  WARMUP_STEPS: 2.0
  WEIGHT_DECAY: 0.004
OUT_DIR: /mnt/Work/Dataset/GEBD/train_logs/20230214_004945
RNG_SEED: 1
TEST:
  BATCH_SIZE: 8
  WEIGHTS: ''
TRAIN:
  BATCH_SIZE: 8
  EPOCHS: 10
  MIXED_PRECISION: true
  WEIGHTS: ''
VERBOSE: true
